sudo: required
services:
  - docker

before_install:
  - docker build -t cneil89/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true cneil89/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Docker-react-env"
  bucket_name: "elasticbeanstalk-us-east-1-902505664412"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_ACCESS_KEY: "$AWS_SECRET_KEY"